---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Echo "Hello World"
    command: echo "Hello World"

  - name: install packages
    package:
      name: dconf-editor
      name: gnome-tweaks tilix
      name: vlc
      name: gimp