---
- hosts: localhost
  connection: local
  become: true
  vars_prompt:
    - name: passphrase
      prompt: Enter Passphase
      private: no
  tasks:
    - include: tasks/packages.yml
    - include: tasks/users.yml
    - include: tasks/cronjobs.yml
    - include: tasks/filecopies.yml