---
- hosts: localhost
  connection: local
  become: true
  tasks:
    - include: tasks/packages.yml
    - include: tasks/users.yml
    - include: tasks/cronjobs.yml
    - include: tasks/filecopies.yml