---
- hosts: localhost
  tasks:
    - name: install packages
      become: true
      become_user: root
      dnf:
        state: present
        name:
         - dconf-editor
         - gnome-tweaks tilix
         - vlc
         - gimp

    - name: Echo "Hello World"
      command: echo "Hello World"

    - name: remove openoffice
      become: true
      become_user: root 
      dnf:
        state: absent
        name: 
       - openoffice
       - espeak
       - qemu

