---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Echo "Hello World"
    command: echo "Hello World"

  - name: install packages
    package:
      name:
        - dconf-editor
        - gnome-tweaks tilix
        - vlc
        - gimp

  - name: remove openoffice 
    package:
      name: openoffice
      state: absent

  - name: remove espeak 
    package:
      name: espeak
      state: absent

  - name: remove qemu
    package:
      name: qemu
      state: absent
