---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name: htop

  - name: remove package 
    package:
      name:
      state: absent

  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/.bashrc
      owner: root
      group: root
  
  - name: add I17admin
    user:
      name: I17admin
      system: yes
  
  - name: set up sudo for I17admin
    copy:
      src: files/sudoer_I17admin
      dest: /etc/sudoers.d/I17admin
      owner: root
      group: root
      mode: 0440
  
  - name: add updater-ansible pull cron job
    cron:
      name: ansible auto-update
      user: I17admin
      minute: "*90"
      job: ansible-pull -o -U https://github.com/JohannesLbck/I17AnsiblePCLab.git
      
  - name: copy wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /user/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    become_user: root
    dconf:
      key: ?
      value: "'file://user/share/backgrounds/ansible-wallpaper.png'"      

  - name: enable Night Light
    dconf:
      key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
      vallue: true
  
  - name: Copy a file to the pc
    copy:
      src: files/placeholder.txt
      dest: /home/placeholder/

  - name: Enable Flathub repository
    command: flapak remote-add --if-not-exists flahub https://flathub.org/repo/flathub.flappakrepo

  - name: Install I forgot the name of the office package :D
    command: flatpak install --assumeyes flathub >insert name<

  - name: set file access using the command I forgot
    command: xxxx yyy zzz