---
- name: install packages
  dnf:
    state: present
    name: 
     - dconf-editor
     - gimp
     - cronie
     - snapd
     - graphviz  
- name: Enable Flathub repository
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
- name: Install wps
  command: flatpak install --assumeyes flathub wps

- name: set file access for wps
  command: flatpak override com.wps.Office --filesystem=home

- name: update all packages
  dnf:
    name: "*"
    state: latest

- name: set up snap
  command: ls -s /var/lib/snapd/snap /snap
    
- name: install Visual Studio Code
  command: snap install --classic code  
