---
- name: install packages
  dnf:
    state: present
    name: 
     - dconf-editor
     - gimp
     - cronie

- name: remove packages
  dnf:
    state: absent
    name:
     - espeak
     - qemu

- name: Enable Flathub repository
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install wps
  command: flatpak install --assumeyes flathub wps

- name: set file access for wps
  command: flatpak override com.wps.Office --filesystem=home

- name: remove libreoffice
  command: sudo dnf remove *libreoffice*

- name: update all packages
  dnf:
    name: "*"
    state: latest
