---
- name: install packages
  dnf:
    state: present
    name: 
     - dconf-editor
     - gimp
     - cronie
     - snapd
- name: Enable Flathub repository
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install wps
  command: flatpak install --assumeyes flathub wps

- name: set file access for wps
  command: flatpak override com.wps.Office --filesystem=home

- name: remove libreoffice
  command: dnf -y remove *libreoffice* *qemu* *espeak*

- name: update all packages
  dnf:
    name: "*"
    state: latest
- name: install Visual Studio Code
  command: sudo snap install --classic code  
