---
- name: add repository  key
  command: sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
- name: add repository
  command: sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
- name: install packages
  dnf:
    state: present
    name: 
     - dconf-editor
     - gimp
     - cronie
     - snapd
     - graphviz
     - code
- name: Enable Flathub repository
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
- name: Install wps
  command: flatpak install --assumeyes flathub wps

- name: set file access for wps
  command: flatpak override com.wps.Office --filesystem=home

- name: update all packages
  dnf:
    name: "*"
    state: latest
