- name: create ansible user
  user:
    name: I17PCLab
    system: yes
    
- name: set up sudo for I17PCLab
  copy:
    src: files/sudoer_I17PCLab
    dest: /etc/sudoers.d/I17PCLab
    owner: root
    group: root
    mode: 0440
    generate_ssh_key: yes