- name: set up sudo for I17PCLab
  copy:
    src: files/sudoer_I17PCLab
    dest: /etc/sudoers.d/I17PCLab
    owner: root
    group: root
    mode: 0440

- name: set up autologin
  copy:
    src: files/custom.conf
    dest: /etc/gdm
    owner: root
    group: root
    mode: 0440
       
- name: set up ssh for users
  user:
    name: I17PCLab
    state: present
    generate_ssh_key: yes

   